#!/bin/sh

if [ "x${RUNVALID_PREFIX}" != "x" ];
then
PREFIX=${RUNVALID_PREFIX}
else
PREFIX=../src
fi

echo "---Running tests with the real traces---"
echo ""

echo "Financial: Hybrid Fixed Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-timer-fixed.parv hybrid-timer-fixed.outv ascii financial_trace.txt 0 &
grep "FCL : Response time average:" hybrid-timer-fixed.outv | grep -v "#"

echo "Financial: Hybrid RW Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-timer-rw.parv hybrid-timer-rw.outv ascii financial_trace.txt 0  &
grep "FCL : Response time average:" hybrid-timer-rw.outv | grep -v "#"

echo "Financial: Hybrid Optimal Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-timer-optimal.parv hybrid-timer-optimal.outv ascii financial_trace.txt 0 
grep "FCL : Response time average:" hybrid-timer-optimal.outv | grep -v "#"

echo "Financial: Hybrid Fixed Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-nontimer-fixed.parv hybrid-nontimer-fixed.outv ascii financial_trace.txt 0 &
grep "FCL : Response time average:" hybrid-nontimer-fixed.outv | grep -v "#"

echo "Financial: Hybrid RW Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-nontimer-rw.parv hybrid-nontimer-rw.outv ascii financial_trace.txt 0  &
grep "FCL : Response time average:" hybrid-nontimer-rw.outv | grep -v "#"

echo "Financial: Hybrid Optimal Partitioning  response time should be around 4.140330 ms"
$PREFIX/disksim hybrid-nontimer-optimal.parv hybrid-nontimer-optimal.outv ascii financial_trace.txt 0 &
grep "FCL : Response time average:" hybrid-nontimer-optimal.outv | grep -v "#"

